Repository Vizzuality/landgriffon, pull requests merged in 2021-11, with the labels that each got.

#134 Feature: LANDGRIF-320 Add riskmap deforestation and carbon emissions
  api/src/modules/h3-data/h3-data.repository.ts
  api/src/modules/h3-data/h3-data.service.ts
  api/test/h3-data/h3-risk-map.spec.ts
Labels: ready for review, API

#150 Added fake login and resolved eslint warnings
  client/public/favicon.ico
  client/public/landgriffon-logo.svg
  client/src/components/avatar/component.stories.tsx
  client/src/components/breadcrumb/component.stories.tsx
  client/src/components/button/component.stories.tsx
  client/src/components/chart/area-stacked/component.tsx
  client/src/components/chart/component.stories.tsx
  client/src/components/forms/select/component.stories.tsx
  client/src/components/loading/component.stories.tsx
  client/src/components/map/controls/component.stories.tsx
  client/src/components/map/controls/zoom/component.stories.tsx
  client/src/components/widget/component.stories.tsx
  client/src/containers/.gitkeep
  client/src/containers/logo/component.tsx
  client/src/containers/logo/index.ts
  client/src/containers/mobile-header/component.tsx
  client/src/containers/mobile-header/index.ts
  client/src/layouts/application/component.tsx
  client/src/layouts/authentication/component.tsx
  client/src/lib/hooks/analysis/index.ts
  client/src/lib/hooks/h3-data/index.ts
  client/src/lib/hooks/scenarios/index.ts
  client/src/lib/hooks/users/index.ts
  client/src/pages/_document.tsx
  client/src/pages/analysis/index.tsx
  client/src/pages/api/auth/[...nextauth].ts
  client/src/pages/auth/sign-in.tsx
  client/src/pages/index.tsx
  client/tailwind.config.js
Labels: front-end

#155 removes unnecessary bio datasets and updates harvested area
  api/src/modules/geo-regions/geo-region.entity.ts
  data/Makefile
  data/data_download/populate_admin_regions.sql
  data/h3_raster_importer/Makefile
Labels: ready for review

#157 material is optional; fixed data missing
  client/src/hooks/h3-data/index.ts
  client/src/store/features/analysis/selector.ts
  client/src/types.d.ts
Labels: front-end

#163 Fixes for bugs before the demo
  client/src/containers/analysis-visualization/analysis-filters/more-filters/component.tsx
  client/src/containers/analysis-visualization/analysis-map/component.tsx
Labels: front-end

#164 fixed mode control selector #LANDGRIF-349
  client/src/containers/analysis-visualization/layer-control/component.tsx
  client/src/containers/analysis-visualization/mode-control/component.tsx
Labels: front-end
