Repository Vizzuality/landgriffon, pull requests merged in 2021-06, with the labels that each got.

#19 first steps carbon metric and risk map
  data/notebooks/Lab/4_carbon_indicator_v2.ipynb
Labels: Ready for Review

#24 chore: LANDGRIF-45 - Configure Docker for Frontend
  Makefile
  client/Dockerfile
  client/entrypoint.sh
  docker-compose.yml
  env.default
Labels: DevOps, Ready for Review

#32 chore: LANDGRIF-134 Create Admin-Regions / Geo-Regions modules, entities
  api/package.json
  api/src/app.module.ts
  api/src/modules/admin-regions/admin-regions.entity.ts
  api/src/modules/admin-regions/admin-regions.module.ts
  api/src/modules/admin-regions/admin-regions.repository.ts
  api/src/modules/geo-regions/geo-regions.entity.ts
  api/src/modules/geo-regions/geo-regions.module.ts
  api/src/modules/geo-regions/geo-regions.repository.ts
  api/yarn.lock
Labels: API, Ready for Review
