Repository Vizzuality/landgriffon, pull requests merged in 2022-03, with the labels that each got.

#277 Added user dropdown in the sidebar menu
  client/src/containers/UserDropdown/component.tsx
  client/src/containers/sidebar/component.tsx
  client/src/containers/string-avatar/component.tsx
  client/src/containers/string-avatar/type.d.ts
  client/src/containers/user-dropdown/component.tsx
  client/src/containers/user-dropdown/index.ts
  client/src/pages/api/auth/[...nextauth].ts
Labels: ready for review, front-end

#279 added next auth secret env variable
  .github/workflows/publish-docker-images.yml
  client/.env.sample
  client/Dockerfile
  client/docs/installation.stories.mdx
Labels: DevOps, ready for review

#280 Fixed authentication on Vercel
  client/src/pages/api/auth/[...nextauth].ts
Labels: WIP, front-end

#283 Added spinner to the submit buttons
  client/src/components/button/component.tsx
  client/src/pages/auth/sign-in.tsx
  client/src/pages/auth/sign-up.tsx
Labels: ready for review, front-end

#278 fix: prevent dates comp re-render
  client/src/components/select/component.tsx
  client/src/containers/filters/years-range/component.tsx
  client/src/containers/filters/years-range/hooks.ts
  client/src/store/features/analysis/index.ts
Labels: WIP, front-end

#288 user dropdown using popper
  client/package.json
  client/src/containers/user-dropdown/component.tsx
  client/yarn.lock
Labels: WIP, front-end

#305 Fixed years selector for analysis map
  client/src/components/select/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/years-range/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/years-range/index.ts
  client/src/containers/analysis-visualization/analysis-filters/years/component.tsx
Labels: ready for review, front-end

#307 Update scenario
  client/src/components/forms/index.ts
  client/src/containers/scenarios/edit/component.tsx
  client/src/hooks/scenarios/index.ts
Labels: front-end

#316 fix typos on materials csv
  data/base_data_importer/data/4.material.csv
Labels: ready for review

#302 Fixing popover position for scenarios contextual actions
  client/src/containers/scenarios/item/component.tsx
Labels: ready for review, front-end

#324 Intervention creation
  client/src/layouts/analysis/component.tsx
Labels: WIP, front-end

#329 data for create intervention form connected to API
  client/src/containers/interventions/new/step1/component.tsx
  client/src/hooks/business-units/index.ts
  client/src/types.d.ts
Labels: front-end

#334 fixed error 500 in the search for admin page
  client/src/pages/_app.tsx
Labels: bugfix, front-end

#336 Added pagination for table in analysis page
  client/src/containers/analysis-visualization/analysis-table/single-indicator-table/component.tsx
Labels: ready for review, front-end

#340 error for delete scenario
  client/src/containers/scenarios/filters/component.tsx
  client/src/containers/scenarios/item/component.tsx
Labels: front-end, don't merge

#343 fixed scrollref for infinite query
  client/src/containers/scenarios/component.tsx
  client/src/hooks/scroll/index.ts
Labels: front-end
