Repository Vizzuality/landgriffon, pull requests merged in 2022-01, with the labels that each got.

#205 chore/LANDGRIF-393 - Update Unit Conversion value on water risk map calculation
  api/src/modules/h3-data/h3-data.repository.ts
  api/test/e2e/h3-data/mocks/h3-risk-map-calculation-results.ts
Labels: ready for review, API

#209 Fixed materials and suppliers for more filters selections
  client/src/containers/analysis-visualization/analysis-filters/more-filters/component.tsx
  client/src/containers/analysis-visualization/analysis-table/indicator-table/component.tsx
Labels: front-end

#215 added custom table for grouping indicators on the table view
  client/src/components/table/component.tsx
  client/src/containers/analysis-visualization/analysis-table/component.tsx
  client/src/containers/analysis-visualization/analysis-table/multiple-indicator-table/component.tsx
  client/src/containers/analysis-visualization/analysis-table/multiple-indicator-table/index.tsx
  client/src/containers/analysis-visualization/analysis-table/single-indicator-table/component.tsx
  client/src/containers/analysis-visualization/analysis-table/single-indicator-table/index.tsx
Labels: front-end

#212 add prototype for getting distributed impact map
  data/notebooks/Lab/Distributed_impact_prototype_v1.ipynb
Labels: WIP
