Repository Vizzuality/landgriffon, pull requests merged in 2022-11, with the labels that each got.

#732 (feat) LANDGRIF-959 calculate impact for active indicators 2
  api/src/modules/impact/services/indicator-dependency-getter.service.ts
  api/src/modules/indicator-records/services/impact-calculator.service.ts
  api/src/modules/indicators/indicators.controller.ts
  api/src/modules/indicators/indicators.module.ts
  api/src/modules/scenario-interventions/scenario-intervention.repository.ts
  api/src/modules/scenario-interventions/scenario-interventions.service.ts
  api/src/modules/scenario-interventions/services/intervention-builder.service.ts
Labels: WIP

#735 tooltips: adjusts base z-index
  client/src/components/dropdown/component.tsx
  client/src/components/modal/constants.ts
  client/src/components/tooltip/component.tsx
Labels: front-end

#736 fixed legend colors order in layer comparison
  client/src/hooks/h3-data/impact/comparison.ts
  client/src/hooks/h3-data/utils.ts
  client/src/hooks/layers/impact.ts
  client/src/utils/colors.ts
Labels: front-end

#745 Fixed an issue where scenarioId param was missing in table analysis
  client/CHANGELOG.md
  client/cypress/e2e/analysis-scenarios.cy.ts
  client/package.json
  client/src/containers/analysis-visualization/analysis-table/component.tsx
Labels: ready for review, front-end

#758 Fix invalid url being built when navigating analysis modes
  client/CHANGELOG.md
  client/package.json
  client/src/hooks/queryParam/index.ts
Labels: ready for review, front-end

#766 (feat) LANDGRIF=-987 satelligence indicators
  api/src/migrations/1668073310691-SatelligenceIndicatorCalculations.ts
  api/src/modules/admin-regions/admin-regions.service.ts
  api/src/modules/geo-coding/geo-coding.module.ts
  api/src/modules/geo-coding/geo-coding.service.ts
  api/src/modules/geo-coding/strategies/admin-region-of-production.service.ts
  api/src/modules/import-data/sourcing-data/dto-processor.service.ts
  api/src/modules/import-data/sourcing-data/sourcing-data-import.service.ts
  api/src/modules/indicator-records/indicator-records.module.ts
  api/src/modules/indicator-records/services/impact-calculator.service.ts
  api/src/modules/indicator-records/services/indicator-dependency-manager.service.ts
  api/src/modules/indicators/indicator.entity.ts
  api/src/modules/indicators/indicators.controller.ts
  api/src/modules/indicators/indicators.module.ts
  api/src/modules/indicators/indicators.service.ts
  api/src/modules/sourcing-locations/dto/create.sourcing-location.dto.ts
  api/src/modules/sourcing-locations/sourcing-location.entity.ts
  api/src/modules/sourcing-records/dto/sourcing-records-with-indicator-raw-data.dto.ts
  api/test/e2e/impact/impact-table/impact.spec.ts
  api/test/e2e/sourcing-locations/smart-filters-location-types.spec.ts
  api/test/integration/geo-coding/administrative-region-of-production.geocoding.spec.ts
  api/test/integration/indicators/status-changes/indicator-status-changes.spec.ts
Labels: WIP

#771 adding newsletters email to the subscriber form
  marketing-v2/src/containers/methodology-form/component.tsx
  marketing-v2/src/containers/newsletter/component.tsx
  marketing-v2/src/pages/api/newsletter.ts
  marketing-v2/src/utils/subscribers-spreadsheet.ts
Labels: ready for review, front-end, marketing

#763 removes hardcoded minus sign from comparison chart
  client/CHANGELOG.md
  client/src/containers/analysis-chart/comparison-chart/tooltip/component.tsx
Labels: ready for review, front-end

#767 Replace lodash with lodash-es to decrease bundle size
  client/.eslintrc.js
  client/package.json
  client/src/components/search/component.tsx
  client/src/containers/admin/data-table/component.tsx
  client/src/containers/admin/download-materials-data-button/component.tsx
  client/src/containers/analysis-chart/comparison-chart/component.tsx
  client/src/containers/analysis-chart/comparison-chart/tooltip/component.tsx
  client/src/containers/analysis-chart/impact-chart/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/location-types/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/materials/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/more-filters/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/origin-regions/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/suppliers/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/years-range/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/years/component.tsx
  client/src/containers/analysis-visualization/analysis-map/component.tsx
  client/src/containers/analysis-visualization/analysis-table/component.tsx
  client/src/containers/business-units/select/component.tsx
  client/src/containers/downloader/component.tsx
  client/src/containers/interventions/form/component.tsx
  client/src/containers/locations/select/component.tsx
  client/src/containers/materials/select/component.tsx
  client/src/containers/suppliers/select/component.tsx
  client/src/hooks/scroll/index.ts
  client/src/pages/data/scenarios/index.tsx
  client/src/store/index.ts
  client/yarn.lock
Labels: ready for review, front-end

#769 changed key value in tooltip items of impact chart
  client/CHANGELOG.md
  client/src/containers/analysis-chart/impact-chart/tooltip/component.tsx
Labels: ready for review, front-end

#770 disconnects map from URL changes
  client/CHANGELOG.md
  client/src/containers/analysis-visualization/analysis-map/component.tsx
Labels: ready for review, front-end

#768 updates placeholders of year range selectors
  client/CHANGELOG.md
  client/src/containers/admin/data-table/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/years-range/component.tsx
  client/src/containers/filters/years-range/component.tsx
  client/src/containers/filters/years-range/types.d.ts
Labels: ready for review, front-end

#773 Including newsletter subscription from contact form
  marketing-v2/src/containers/contact/component.tsx
  marketing-v2/src/pages/api/contact.ts
  marketing-v2/src/pages/api/methodology.ts
Labels: ready for review, front-end, marketing

#772 Feedback after the user requests to download the methodology
  marketing-v2/src/containers/methodology-form/component.tsx
Labels: ready for review, front-end, marketing

#775 removed document selection in methodology form
  marketing-v2/src/containers/methodology-form/component.tsx
  marketing-v2/src/containers/methodology/steps/02/component.tsx
  marketing-v2/src/pages/api/methodology.ts
Labels: ready for review, front-end, marketing

#781 (bugfix) LANDGRIF-1070 NaN values on impact values
  api/src/modules/indicator-records/indicator-record.entity.ts
  api/src/modules/indicator-records/services/impact-calculator.service.ts
  api/src/modules/scenario-interventions/scenario-intervention.repository.ts
  api/test/e2e/scenarios/scenarios.spec.ts
  api/test/integration/indicator-record/calculations/indicator-records.service.spec.ts
  api/test/integration/indicator-record/validations/indicator-record.validations.spec.ts
Labels: bugfix

#776 Filtering and updating the scenario comparison selector
  client/CHANGELOG.md
  client/package.json
  client/src/components/forms/select/component.tsx
  client/src/containers/analysis-sidebar/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/more-filters/component.tsx
  client/src/containers/scenarios/comparison/component.tsx
Labels: front-end

#793 Update location types
  api/src/modules/admin-regions/dto/get-admin-region-tree-with-options.dto.ts
  api/src/modules/business-units/dto/get-business-unit-tree-with-options.dto.ts
  api/src/modules/geo-coding/geo-coding.service.ts
  api/src/modules/h3-data/dto/get-impact-map.dto.ts
  api/src/modules/h3-data/h3-data-map.repository.ts
  api/src/modules/impact/dto/impact-table.dto.ts
  api/src/modules/import-data/sourcing-data/dto-processor.service.ts
  api/src/modules/import-data/sourcing-data/validators/address-input.custom.validator.ts
  api/src/modules/import-data/sourcing-data/validators/latitude-input.custom.validator.ts
  api/src/modules/import-data/sourcing-data/validators/longitude-input.custom.validator.ts
  api/src/modules/import-data/sourcing-data/validators/sourcing-data.class.validator.ts
  api/src/modules/materials/dto/get-material-tree-with-options.dto.ts
  api/src/modules/scenario-interventions/dto/create.scenario-intervention.dto.ts
  api/src/modules/scenario-interventions/dto/custom-validators/address-input.custom.validator.ts
  api/src/modules/scenario-interventions/dto/custom-validators/latitude-input.custom.validator.ts
  api/src/modules/scenario-interventions/dto/custom-validators/longitude-input.custom.validator.ts
  api/src/modules/sourcing-locations/dto/location-type.sourcing-locations.dto.ts
  api/src/modules/sourcing-locations/helpers/location-type.parser.ts
  api/src/modules/sourcing-locations/sourcing-location.entity.ts
  api/src/modules/suppliers/dto/get-supplier-tree-with-options.dto.ts
  api/src/utils/transform-location-type.util.ts
  api/test/e2e/admin-regions/admin-regions-tree-smart-filters.spec.ts
  api/test/e2e/business-units/business-unit-tree-smart-filters.spec.ts
  api/test/e2e/h3-data/h3-impact-map.spec.ts
  api/test/e2e/h3-data/mocks/h3-impact-map.mock.ts
  api/test/e2e/impact/impact-table/impact.spec.ts
  api/test/e2e/impact/mocks/response-mocks.impact.ts
  api/test/e2e/materials/materials-tree-smart-filters.spec.ts
  api/test/e2e/scenario-interventions/scenario-interventions.spec.ts
  api/test/e2e/sourcing-locations/smart-filters-location-types.spec.ts
  api/test/e2e/sourcing-locations/sourcing-locations-materials.spec.ts
  api/test/e2e/suppliers/suppliers-smart-filters.spec.ts
  api/test/integration/import-data/xlsx-uploads/base-dataset-location-errors.xlsx
  api/test/integration/import-data/xlsx-uploads/import-data-controller-validations.spec.ts
  api/test/integration/import-data/xlsx-uploads/sourcing-data-import.spec.ts
  api/test/integration/import-data/xlsx-uploads/test-base-dataset.xlsx
Labels: WIP

#796 Removing horizontal scroll in legend items
  client/CHANGELOG.md
  client/src/components/legend/item/component.tsx
  client/src/containers/analysis-visualization/analysis-legend/component.tsx
Labels: front-end

#804 Fix tree select crash
  client/src/components/tree-select/component.tsx
Labels: front-end

#805 Single tree select style
  client/src/components/tree-select/component.tsx
  client/src/components/tree-select/utils.ts
Labels: front-end
