Repository Vizzuality/landgriffon, pull requests merged in 2022-06, with the labels that each got.

#440 fixing bug, sidebar button expanding
  client/CHANGELOG.md
  client/src/layouts/analysis/component.tsx
Labels: bug, ready for review, front-end

#429 interactivity to legend area chart
  client/CHANGELOG.md
  client/src/components/chart/area-stacked/component.tsx
  client/src/containers/analysis-visualization/analysis-chart/component.tsx
Labels: front-end

#443 Forcing desktop version in mobile devices
  client/CHANGELOG.md
  client/src/pages/_document.tsx
Labels: ready for review, front-end

#449 Chore: Increase frontend file size limit
  client/CHANGELOG.md
  client/src/constants/file-uploader-size-limits.ts
Labels: front-end

#450 location types standard and param added to impact endpoint
  client/CHANGELOG.md
  client/src/containers/analysis-visualization/analysis-filters/location-types/component.tsx
  client/src/containers/interventions/new/step2/supplier/component.tsx
  client/src/hooks/h3-data/index.ts
  client/src/hooks/interventions/index.ts
  client/src/hooks/materials/index.ts
  client/src/utils/string.ts
Labels: ready for review, front-end

#444 Improve-UX-login
  client/CHANGELOG.md
  client/src/layouts/authentication/component.tsx
  client/src/pages/auth/sign-in.tsx
Labels: front-end

#463 Removed mobile version
  client/src/containers/sidebar/component.tsx
  client/src/layouts/application/component.tsx
Labels: ready for review, front-end

#469 group by standarised params
  client/CHANGELOG.md
  client/src/containers/analysis-visualization/analysis-filters/group-by/component.tsx
  client/src/styles/globals.css
Labels: front-end

#472 number of rows in table updated - fix
  client/CHANGELOG.md
  client/src/components/table/component.tsx
  client/src/components/table/types.d.ts
  client/src/containers/analysis-visualization/analysis-table/component.tsx
Labels: front-end

#454 table and chart view years range
  client/CHANGELOG.md
  client/src/containers/analysis-visualization/analysis-filters/years-range/component.tsx
Labels: front-end

#481 changelog updated to 2022.06.27 version
  client/CHANGELOG.md
Labels: front-end

#478 collapse btn fixed position
  client/CHANGELOG.md
  client/src/layouts/analysis/component.tsx
Labels: front-end

#480 badge styles
  client/src/components/badge/component.tsx
  client/src/containers/analysis-visualization/analysis-dynamic-metadata/component.tsx
Labels: front-end

#482 Fixed some issues on the table component for admin page
  client/CHANGELOG.md
  client/src/components/table/component.tsx
  client/src/components/table/data-row/component.tsx
  client/src/components/table/data-row/types.d.ts
Labels: front-end

#479 location type params to impact/table
  client/CHANGELOG.md
  client/src/containers/analysis-visualization/analysis-filters/location-types/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/more-filters/component.tsx
  client/src/containers/interventions/new/step2/supplier/component.tsx
  client/src/hooks/interventions/index.ts
  client/src/hooks/location-types/index.ts
  client/src/store/features/analysis/selector.ts
  client/src/types.d.ts
Labels: front-end

#487 dashed line in table to difference projected data
  client/CHANGELOG.md
  client/src/components/table/component.tsx
  client/src/components/table/data-row/component.tsx
  client/src/components/table/data-row/types.d.ts
  client/src/components/table/head-cell-content/component.tsx
  client/src/components/table/summary-row/component.tsx
  client/src/components/table/summary-row/types.d.ts
  client/src/components/table/types.d.ts
  client/src/containers/analysis-visualization/analysis-table/component.tsx
  client/src/containers/analysis-visualization/analysis-table/types.d.ts
Labels: front-end
