Repository Vizzuality/landgriffon, pull requests merged in 2022-08, with the labels that each got.

#557 fixed validation for latitude in the intervention creation form
  client/src/containers/interventions/form/component.tsx
Labels: front-end

#558 fixed coefficients input in the intervention form
  client/CHANGELOG.md
  client/src/containers/interventions/form/component.tsx
Labels: front-end

#551 Marketing/fixes/feedback changes second round
  .DS_Store
  marketing-v2/public/favicon.ico
  marketing-v2/public/images/service/blogpost/01.png
  marketing-v2/public/images/service/blogpost/02.png
  marketing-v2/public/images/service/blogpost/03.png
  marketing-v2/src/components/blog-card/component.tsx
  marketing-v2/src/components/blog-card/index.ts
  marketing-v2/src/components/carousel/component.tsx
  marketing-v2/src/containers/blog-posts/component.tsx
  marketing-v2/src/containers/blog-posts/index.ts
  marketing-v2/src/containers/home/what/component.tsx
  marketing-v2/src/containers/privacy-policy/component.tsx
  marketing-v2/src/containers/privacy-policy/index.ts
  marketing-v2/src/containers/the-service/component.tsx
  marketing-v2/src/pages/privacy-policy.tsx
  marketing-v2/src/styles/globals.css
  marketing-v2/tailwind.config.js
Labels: front-end, marketing

#577 Allow crawlers in robots.txt
  client/public/robots.txt
Labels: front-end

#595 intervention form: fixes address input validation
  client/src/containers/interventions/form/component.tsx
  client/src/containers/interventions/utils.ts
Labels: bugfix
