Repository Vizzuality/landgriffon, pull requests merged in 2022-10, with the labels that each got.

#665 Added projected data in line-charts when a comparison is enabled
  client/src/containers/analysis-chart/comparison-chart/component.tsx
  client/src/types.d.ts
Labels: front-end

#652 Sendgrid key change for Methodology form
  marketing-v2/src/pages/api/methodology.ts
Labels: front-end, marketing

#683 renamed admin section to data
  client/cypress/e2e/intervention-creation.cy.ts
  client/cypress/e2e/scenario-creation.cy.ts
  client/cypress/e2e/scenarios.cy.ts
  client/cypress/support/commands.ts
  client/next.config.js
  client/src/containers/analysis-sidebar/component.tsx
  client/src/containers/interventions/form/component.tsx
  client/src/containers/scenarios/card/component.tsx
  client/src/containers/scenarios/form/component.tsx
  client/src/containers/scenarios/item/component.tsx
  client/src/layouts/application/component.tsx
  client/src/layouts/data/component.tsx
  client/src/layouts/data/constants.ts
  client/src/layouts/data/index.ts
  client/src/layouts/data/types.d.ts
  client/src/middleware.ts
  client/src/pages/data/index.tsx
  client/src/pages/data/scenarios/[scenarioId]/edit.tsx
  client/src/pages/data/scenarios/[scenarioId]/interventions/[interventionId]/edit.tsx
  client/src/pages/data/scenarios/[scenarioId]/interventions/new.tsx
  client/src/pages/data/scenarios/index.tsx
  client/src/pages/data/scenarios/new.tsx
  client/src/pages/data/settings.tsx
  client/src/pages/data/targets.tsx
  client/src/pages/data/users.tsx
Labels: front-end

#689 fixed more filters
  client/src/containers/analysis-visualization/analysis-map/component.tsx
  client/src/layouts/analysis/component.tsx
Labels: front-end

#692 Fixed an issue where canceling the intervention creation was redirect…
  client/CHANGELOG.md
  client/src/containers/interventions/form/component.tsx
Labels: front-end

#702 Client/fix/redirect from scenario card
  client/src/containers/analysis-sidebar/component.tsx
  client/src/containers/scenarios/comparison/component.tsx
Labels: front-end

#715 added youtube video in The service page
  marketing-v2/src/containers/the-service/hero/component.tsx
Labels: front-end

#723 fixes crash produced by query caching
  client/src/hooks/indicators/index.ts
Labels: front-end

#725 Fixed an issue where tooltip in comparison was breaking the page
  client/CHANGELOG.md
  client/src/containers/analysis-chart/comparison-chart/tooltip/component.tsx
Labels: ready for review, front-end

#726 Added pagination to users table
  client/CHANGELOG.md
  client/src/hooks/users/index.ts
  client/src/pages/data/users.tsx
  client/src/types.d.ts
Labels: front-end
