Repository Vizzuality/landgriffon, pull requests merged in 2023-01, with the labels that each got.

#823 (feat) LANDGRIF-1011 Implement RBAC 2.1
  api/src/main.ts
  api/src/modules/authentication/authentication.service.ts
  api/src/modules/authorization/role.entity.ts
  api/src/modules/users/dto/create.user.dto.ts
  api/src/modules/users/dto/update.user.dto.ts
  api/src/modules/users/users.controller.ts
  api/test/e2e/authentication/auth.spec.ts
  api/test/e2e/users/users.spec.ts
Labels: WIP

#836 Chore/assign default permissions
  api/src/app.module.ts
  api/src/main.ts
  api/src/modules/authentication/authentication.module.ts
  api/src/modules/authentication/authentication.service.ts
  api/src/modules/authorization/authorization.module.ts
  api/src/modules/authorization/authorization.service.ts
  api/src/modules/authorization/permissions/permissions.entity.ts
  api/src/modules/authorization/role.seeder.ts
  api/src/modules/authorization/roles/role.entity.ts
  api/src/modules/users/users.controller.ts
  api/test/e2e/users/users.spec.ts
  api/test/utils/application-manager.ts
Labels: WIP

#838 Showing scenario names in the chart views
  client/CHANGELOG.md
  client/src/containers/analysis-chart/comparison-chart/legend/component.tsx
Labels: front-end

#841 Conditionally add relative unit to map response
  api/src/modules/h3-data/h3-data-map.service.ts
  api/src/modules/h3-data/h3-data.repository.ts
  api/test/e2e/h3-data/h3-impact-map.spec.ts
Labels: WIP, bugfix
