Repository Vizzuality/landgriffon, pull requests merged in 2023-02, with the labels that each got.

#855 [LANDGRIF-1145]: fixes undefined endYear value
  client/CHANGELOG.md
  client/src/containers/interventions/types.d.ts
  client/src/containers/interventions/utils.ts
Labels: front-end

#847 [LANDGRIF-1141]: fixes `material` type layer fetching from the wrong endpoint
  client/CHANGELOG.md
  client/src/containers/analysis-visualization/analysis-filters/years-range/component.tsx
  client/src/containers/analysis-visualization/analysis-filters/years/component.tsx
  client/src/containers/analysis-visualization/analysis-legend/material-legend-item/component.tsx
  client/src/containers/years/component.tsx
  client/src/hooks/years/index.ts
  client/src/store/features/analysis/map.ts
Labels: front-end

#849 Remove default active indicators filter for various endpoints
  api/src/modules/impact/impact.controller.ts
  api/src/modules/impact/impact.module.ts
  api/src/modules/indicator-records/services/impact-calculator.service.ts
  api/src/modules/indicators/indicator.repository.ts
  api/src/modules/indicators/indicators.service.ts
  api/test/e2e/impact/impact-table/impact.spec.ts
  api/test/e2e/indicators/indicators.spec.ts
  api/test/integration/indicators/status-changes/indicator-status-changes.spec.ts
Labels: WIP

#850 (chore) LANDGRIF-1146 - Tiler integration
  .editorconfig
  .github/workflows/testing-tiler.yml
  api/config/custom-environment-variables.json
  api/config/default.json
  api/config/development.json
  api/config/test.json
  api/src/modules/authentication/authentication.controller.ts
  api/src/modules/authorization/modules/scenarios.access-control.service.ts
  api/src/modules/scenarios/scenario.entity.ts
  docker-compose.yml
  infrastructure/kubernetes/.terraform.lock.hcl
  tiler/.env.default
  tiler/Dockerfile
  tiler/__init__.py
  tiler/app/__init__.py
  tiler/app/config/__init__.py
  tiler/app/config/config.py
  tiler/app/main.py
  tiler/app/middlewares/__init__.py
  tiler/app/middlewares/auth_middleware.py
  tiler/app/middlewares/url_injector.py
  tiler/app/test/__init__.py
  tiler/app/test/test_health.py
  tiler/requirements.txt
Labels: WIP

#871 [LANDGRIF-1222]: user unable to sign up for the platform
  client/CHANGELOG.md
  client/cypress/e2e/sign-up.cy.ts
  client/cypress/fixtures/auth/sign-up.json
  client/src/pages/auth/signup.tsx
Labels: front-end

#865 [LANDGRIF-1208]: omits scenarioId param from /h3/map/impact/compare endpoint
  client/CHANGELOG.md
  client/src/hooks/layers/impact.ts
Labels: front-end

#869 [LANGRIF-1125]: Add role check to enable upload data source button
  client/CHANGELOG.md
  client/cypress/e2e/data.cy.ts
  client/cypress/fixtures/profiles/admin.json
  client/src/containers/admin/data-table/component.tsx
Labels: front-end

#874 [LANDGRIF-680] add qa raster to h3 data notebook
  data/notebooks/Lab/QA_h3_vs_raster_calculations.ipynb
Labels: science

#876 Ensuring material contextual layer has resolution fixed to 4
  client/CHANGELOG.md
  client/cypress/e2e/analysis-map.cy.ts
  client/cypress/fixtures/layers/material-layer.json
  client/cypress/fixtures/materials/show.json
  client/src/components/tree-select/component.tsx
  client/src/containers/analysis-visualization/analysis-legend/settings/materialSettings.tsx
  client/src/hooks/h3-data/material.ts
Labels: front-end

#880 Test specs re-organization
  client/cypress.config.ts
  client/cypress/e2e/analysis-chart.cy.ts
  client/cypress/e2e/analysis-filters.cy.ts
  client/cypress/e2e/analysis-map.cy.ts
  client/cypress/e2e/analysis-nav.cy.ts
  client/cypress/e2e/analysis-scenarios.cy.ts
  client/cypress/e2e/analysis-table.cy.ts
  client/cypress/e2e/analysis.cy.ts
  client/cypress/e2e/data.cy.ts
  client/cypress/e2e/intervention-creation.cy.ts
  client/cypress/e2e/intervention-edition.cy.ts
  client/cypress/e2e/scenario-creation.cy.ts
  client/cypress/e2e/scenarios.cy.ts
  client/cypress/support/commands.ts
  client/cypress/support/index.d.ts
Labels: front-end

#895 [LANDGRIF-1250]: location type selector holds value after closing popover
  client/CHANGELOG.md
  client/src/components/forms/select/types.d.ts
  client/src/containers/analysis-visualization/analysis-filters/more-filters/component.tsx
Labels: front-end, hotfix

#897 fixes regression when location type is selected
  client/src/containers/analysis-visualization/analysis-filters/more-filters/component.tsx
Labels: front-end, hotfix
