Repository Vizzuality/landgriffon, pull requests merged in 2023-03, with the labels that each got.

#912 removes duplicated tests in analysis spec
  client/cypress/e2e/analysis.cy.ts
Labels: front-end

#910 [LANDGRIF-1246]: fixes weird behaviour of coefficients panel
  client/CHANGELOG.md
  client/src/containers/interventions/form/component.tsx
Labels: front-end

#917 Dockerfile: removes next-env.d.ts
  client/Dockerfile
Labels: front-end

#899 [LANDGRIF-1262] Refactor (removes) `tiff_to_h3_table.py` to something more modular
  data/.env.example
  data/.pre-commit-config.yaml
  data/data.sh
  data/docker-compose.yml
  data/h3_data_importer/Makefile
  data/h3_data_importer/raster_folder_to_h3_table.py
  data/h3_data_importer/utils.py
  data/h3_data_importer/vector_folder_to_h3_table.py
  data/notebooks/Lab/10_Met_v0.1_results.ipynb
  data/requirements.txt
  data/setup.cfg
  data/test_environment.py
  data/tox.ini
Labels: nightmare, science

#928 fixed alignment for categorical legends
  client/CHANGELOG.md
  client/src/components/legend/types/categorical/component.tsx
  client/src/containers/analysis-visualization/analysis-legend/contextual-legend-item/component.tsx
Labels: front-end

#918 fix: Display error messages
  client/package.json
  client/src/containers/scenarios/card/component.tsx
  client/src/pages/data/scenarios/[scenarioId]/edit.tsx
  client/src/pages/data/scenarios/[scenarioId]/interventions/[interventionId]/edit.tsx
  client/src/pages/data/scenarios/[scenarioId]/interventions/new.tsx
  client/src/pages/data/scenarios/new.tsx
  client/src/services/api.ts
  client/src/types.d.ts
  client/src/utils/handle-response-error.ts
  client/yarn.lock
Labels: bug, front-end

#924 fixed callback url after logout
  client/CHANGELOG.md
  client/src/containers/user-dropdown/component.tsx
Labels: front-end
